### ISSUE TITLE
cssmin is optimizing multiple background rules incorrectly

### ISSUE THREAD

**Issue by codeability-ab** [gruntjs/grunt-contrib-cssmin#106]
Hello!

cssmin optimizes code incorrectly when shorthand property `background` is used in combination with specific properties like `background-position` and `background-repeat`.

Problem occurs when multiple images are specified.

**CSS code**

``` css
.test {
    background:url(icon1.png), url(icon2.png);
    background-repeat: no-repeat, no-repeat;
    background-size: 20px 20px, 20px 20px;
    background-position: 20px 20px, 50px 50px;
}
```

**After cssmin**

``` css
.test {
    background: url(icon1.png), url(icon2.png) no-repeat,no-repeat 20px 20px, 50px 50px;
    background-size: 20px 20px,20px 20px
}
```

cssmin moves the `background-repeat` and `background-position` rules in a way that messes up the `background` rule!

I can get around the problem with the following changes

``` css
.test {
    background:url(icon1.png) no-repeat 20px 20px,url(icon2.png) no-repeat 50px 50px;
    background-size:20px 20px,20px 20px;
}
```

Maybe it's bad practice to use the shorthand property `background` in combination with `background-position` and `background-repeat`? Thought you might be interested anyway..!

Best regards Johan
