### ISSUE TITLE
css替换问题

### ISSUE THREAD

**Issue by xuexb** [gruntjs/grunt-contrib-cssmin#116]
Thank you...

源css:

``` css
a{
    background-color:#fff;
    *background-color:#ccc;
    _background-color:#fff;
}
```

替换后:

``` css
a{background-color:#fff}
```

这不科学啊...
