### ISSUE TITLE
Css property display: -webkit-box; disappear after cssmin

### ISSUE THREAD

**Issue by g8up** [gruntjs/grunt-contrib-cssmin#127]
Before:

``` css
#footer {
    display: -webkit-box;
    -webkit-box-align: center;
    display: -ms-flexbox;
    -ms-box-align: center;
}
```

After:

``` css
#footer{-webkit-box-align:center;display:-ms-flexbox;-ms-box-align:center}
```

`{
  "name": "grunt-contrib-cssmin",
  "description": "Compress CSS files.",
  "version": "0.10.0",
  ...
}`
