### ISSUE TITLE
0.12.0 Pathing Different Than 0.11.0

### ISSUE THREAD

**Issue by tony99nyr** [gruntjs/grunt-contrib-cssmin#173]
With the same configuration we have noticed that the relative pathing is different from 0.11.0 to 0.12.0 and breaks our font-awesome import.  Hopefully this is enough information to debug on your side.

Our grunt config:
```js
cssmin: {
    dist: {
        expand: true,
        cwd: '.tmp/styles/',
        src: ['*.css'],
        dest: 'dist/styles/'
    }
}
```

The `font-awesome.css` source located in `.tmp/bower_components/font-awesome/`:

```css
@font-face {
    font-family: 'FontAwesome';
    src: url('../fonts/fontawesome-webfont.eot?v=4.2.0');
    ...
}
```

The font-awesome file is imported from a css file in `.tmp/styles` with:
`@import "../bower_components/font-awesome/css/font-awesome.css";`

0.11.0 outputs the following which works as expected:
```css
@font-face{
    font-family:FontAwesome;
    src:url(../bower_components/font-awesome/fonts/fontawesome-webfont.eot?v=4.2.0);
    ...
}
```
0.12.0 outputs the following which breaks the paths to all font files:
```css
@font-face{
    font-family:FontAwesome;
    src:url(.tmp/bower_components/font-awesome/fonts/fontawesome-webfont.eot?v=4.2.0);
    ...
}
```
