### ISSUE TITLE
Quotes not preserverd in url()

### ISSUE THREAD

**Issue by frenzis** [gruntjs/grunt-contrib-cssmin#177]
In 0.11.0 the quotes wrapping a url with space were preserved, so the space between 'Open' and 'Sans' in `Open Sans`
```css
url('/build/fonts/Open Sans_normal_400_default.woff')
```
in
```css
@font-face {
[..]
    src: local('Open Sans'),local('OpenSans'),url('/build/fonts/Open Sans_normal_400_default.woff') format('woff');
}
```
was preserved.

In 0.12.0 the quotes are missing, so the final output became
```css
url(/build/fonts/Open Sans_normal_400_default.woff)
```
preventing fonts to load.
