### ISSUE TITLE
Some properties getting dropped on minification

### ISSUE THREAD

**Issue by koolkatwebdesigns** [gruntjs/grunt-contrib-cssmin#230]
In my CSS I have:
.site-title {
  font-family: "SnellRoundhandW01-Scrip", cursive;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}

The resulting minified file has:
site-title{font-family:SnellRoundhandW01-Scrip,cursive}

**Comment by mattgerstman** [comment]
+1

**Comment by markmiro** [comment]
I've run into a similar issue.

```css
.a, .b { display:-webkit-flex }
.a { display:flex }
.b { display:flex }
```

Becomes:
```css
.a,.b{display:flex}
```

**Comment by efender** [comment]
Same problem.

Normal:
```css
.sidebar {
  position: fixed;
  top: 0;
  left: 0;
  background: #379BE6;
  color: #FFF;
}
```
after cssmin:
```css
.sidebar {
  position: fixed;
  top: 0;
}
```
css files - https://dropmefiles.com/D1SLx (before & after)
