### ISSUE TITLE
Code is generally broken

### ISSUE THREAD

**Issue by arc-slate-0** [gruntjs/grunt-contrib-cssmin#264]
I made file wide changes to my CSS and found that the minified code was broken.  I found this out by loading the non-minified code and than the minified code to determine this.  I then looked at the minified code and it appeared to be broken.  The non-minified code looks fine.  Please let me know what information I can provide further.  I updated my CSSMIN but still not go:

I used `ultra-1` as a marker for where things broke b.c. it was visible on my web-site.

**Non-Minified - Works**

```css

/* hidden - for centered number
*/

#ultra-1{
  display: none;
  position: relative;
  width: 100%;
  background: rgba(255, 255, 255, 0.75);
}
#ultra-2{
  position: relative;
  width: 300px;
  height: 100%;
  margin: 0 auto;
}

/* top bar
*/


```

became

**Minified - Broken**
```css
# body_feed,#body_splash,#hold_button,#ultra-1,.toggle_page_lazy,// fixes .ui-dialog-titlebar,
```
