### ISSUE TITLE
Escaped @ symbol handled incorrectly

### ISSUE THREAD

**Issue by leevigraham** [gruntjs/grunt-contrib-cssmin#96]
I was testing cssmin with a class name that included an escaped @ symbol:

``` css
body {
  -moz-box-sizing: border-box;
  box-sizing: border-box;
}

.pad--all0\@sm {
    padding: 0px !important;
}
```

The output of running the `grunt cssmin` task is:

``` css
body{-moz-box-sizing:border-box;box-sizing:border-box}
```

The `.pad--all0\@sm` rule has been removed from the minified css. This can easily be worked around by changing the classname to `pad--all0-at-sm`
